proj1 <- read.table("household_power_consumption.txt", skip = 66637, nrow = 2880, sep = ";")
original_locale <- Sys.getlocale("LC_TIME")
Sys.setlocale("LC_TIME", "C")
colnames(proj1) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
proj1$dt_formatted <- paste("0",sub("/2","/02",proj1$Date),sep="")
proj1$dt_time_formatted <- paste(proj1$dt_formatted, proj1$Time)
proj1$dt_time_formatted <- strptime(proj1$dt_time_formatted, format="%d/%m/%Y %H:%M:%S")
png(filename="plot2.png")
plot(proj1$dt_time_formatted,proj1$Global_active_power,type="l", ylab="Global Active Power (kilowatts)", xlab="")
dev.off()
Sys.setlocale("LC_TIME", original_locale)