proj1 <- read.table("household_power_consumption.txt", skip = 66637, nrow = 2880, sep = ";")
colnames(proj1) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
original_locale <- Sys.getlocale("LC_TIME")
Sys.setlocale("LC_TIME", "C")
proj1$dt_formatted <- paste("0",sub("/2","/02",proj1$Date),sep="")
proj1$dt_time_formatted <- paste(proj1$dt_formatted, proj1$Time)
proj1$dt_time_formatted <- strptime(proj1$dt_time_formatted, format="%d/%m/%Y %H:%M:%S")
png(filename="plot3.png")
plot(proj1$dt_time_formatted,proj1$Sub_metering_1, col = "black", type="l", xlab = "", ylab = "Energy sub metering")
par(new = TRUE)
plot(proj1$dt_time_formatted,proj1$Sub_metering_2, col = "red", type="l", ylab = "",xlab = "", axes = FALSE, ylim= c(0, max(proj1$Sub_metering_1)))
par(new = TRUE)
plot(proj1$dt_time_formatted,proj1$Sub_metering_3, col = "blue", type="l", ylab = "",xlab = "", axes = FALSE, ylim= c(0, max(proj1$Sub_metering_1)))
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), text.col=c("black","black","black"),lty=c(1,1,1), col=c("black","red","blue"))
dev.off()
Sys.setlocale("LC_TIME", original_locale)